theme: minima
author: Guillaume Nurdin
title: I'm a Software Developer
description : Links, blog posts, repo and books to improve Software Development skills

github_username: GuillaumeNurdin
linkedin_username: GuillaumeNurdin
twitter_username: GuillaumeNurdin
header_pages:
  - About.md
  - Soat.md
exclude: ['README.md']
collections:
  - links
  - summaries