author: Guillaume Nurdin
remote_theme: "mmistakes/minimal-mistakes@4.15.2"
repository: guillaumenurdin/guillaumenurdin.github.io
title: I'm a Software Developer
description : Links, blog posts, repo and books to improve Software Development skills
github_username: GuillaumeNurdin
linkedin_username: GuillaumeNurdin
twitter_username: GuillaumeNurdin
url: "http://guillaumenurdin.github.io"
exclude: ['README.md']
include:
  - _pages
collections:
  - links
plugins:
  - jekyll-include-cache
author:
  name     : Guillaume Nurdin
  avatar   : "/assets/images/me.JPG"
  bio      : "Développeur, plutôt .NET, Web et Azure, inspiré par le Software Craftsmanship, Agile, DevOps & Co.<br/>Je travaille chez SOAT."
  location : "Paris, France"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/guillaumenurdin"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/guillaumenurdin/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/guillaumenurdin"
    - label: "SOAT"
      icon: "fas fa-laptop-code"
      url: "http://www.soat.fr"
# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/guillaumenurdin"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/guillaumenurdin"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/guillaumenurdin/"
permalink: /posts/:title/