theme: minima
author: Guillaume Nurdin
title: About Software Development
description : Links, blog posts, repo, books to improve Software Development skills

github_username: GuillaumeNurdin
linkedin_username: GuillaumeNurdin
twitter_username: GuillaumeNurdin
