remote_theme: "mmistakes/minimal-mistakes@4.14.2"
repository: guillaumenurdin/guillaumenurdin.github.io
author: Guillaume Nurdin
remote_theme: "mmistakes/minimal-mistakes@4.14.2"
repository: guillaumenurdin/guillaumenurdin.github.io
title: I'm a Software Developer
description : Links, blog posts, repo and books to improve Software Development skills
github_username: GuillaumeNurdin
linkedin_username: GuillaumeNurdin
twitter_username: GuillaumeNurdin
header_pages:
  - About.md
  - Soat.md
exclude: ['README.md']
collections:
  - links
  - summaries
plugins:
  - jekyll-include-cache
author:
  name     : Guillaume Nurdin
  avatar   : "/assets/images/bio-photo.jpg"
  bio      : "My awesome biography constrained to a sentence or two goes here."
  location : "Somewhere, USA"
